app:
 server:
  port: 8080
 schedule:
  codOfTechnicalOperationWithTrains: 1
  trainNumber: 1
  trainIndex: 5047
  countTrainOnLine: 5
  sequentialNumberOfBrigade: 101
  driverNumber: 4
  codeOfDepartureStation: 1
  codeOfDepartureStationWithBrigade: 1
  departureTime: 2021-04-25 13:03:27
  departureTimeWithBrigade: 2021-04-25 12:40:27
  codeOfArrivalStation: 5
  codeOfArrivalStationWithBrigade: 5
  arrivalTime: 2021-04-25 14:33:27
  arrivalTimeWithBrigade: 2021-04-25 15:30:00
  codeOfHeadWagon: "56"
 station-name:
  - "Андроновка"
  - "Андроновка Оп"
  - "Нижегородская"
  - "Новохохловская"
  - "Угрешская"
  - "Дубровка"
  - "Автозаводская"
  - "Зил"
  - "Верхние котлы"
  - "Крымская"
  - "Площадь Гагарина"
  - "Лужники"
  - "Кутузовская"
  - "Деловой центр"
  - "Шелепиха"
  - "Хорошёво"
  - "Зорге"
  - "Панфиловская"
  - "Стрешнево"
  - "Балтийская"
  - "Коптево"
  - "Лихоборы"
  - "Окружная"
  - "Владыкино"
  - "Ботанический сад"
  - "Ростокино"
  - "Белокаменная"
  - "Бульвар Рокоссовского"
  - "Локомотив"
  - "Измайлово"
  - "Соколиная гора"
  - "Шоссе Энтузиастов"
  - "Андроновка Оп"
  - "Андроновка"
 durationOfTrainStop: 6000
 durationOfBlock: 12000
 drivers:
  - driver1:
     -
