app-stations:
  stations:
    - "Андроновка"
    - "Андроновка Оп"
    - "Нижегородская"
    - "Новохохловская"
    - "Угрешская"
    - "Дубровка"
    - "Автозаводская"
    - "Зил"
    - "Верхние котлы"
    - "Крымская"
    - "Площадь Гагарина"
    - "Лужники"
    - "Кутузовская"
    - "Деловой центр"
    - "Шелепиха"
    - "Хорошёво"
    - "Зорге"
    - "Панфиловская"
    - "Стрешнево"
    - "Балтийская"
    - "Коптево"
    - "Лихоборы"
    - "Окружная"
    - "Владыкино"
    - "Ботанический сад"
    - "Ростокино"
    - "Белокаменная"
    - "Бульвар Рокоссовского"
    - "Локомотив"
    - "Измайлово"
    - "Соколиная гора"
    - "Шоссе Энтузиастов"
    - "Андроновка Оп"
    - "Андроновка"