app:
 server:
  port: 8080
 statin-name:
  - "Андроновка"
  - "Андроновка Оп"
  - "Нижегородская"
  - "Новохохловская"
  - "Угрешская"
  - "Дубровка"
  - "Автозаводская"
  - "Зил"
  - "Верхние котлы"
  - "Крымская"
  - "Площадь Гагарина"
  - "Лужники"
  - "Кутузовская"
  - "Деловой центр"
  - "Шелепиха"
  - "Хорошёво"
  - "Зорге"
  - "Панфиловская"
  - "Стрешнево"
  - "Балтийская"
  - "Коптево"
  - "Лихоборы"
  - "Окружная"
  - "Владыкино"
  - "Ботанический сад"
  - "Ростокино"
  - "Беокаменная"
  - "Бульвар Рокоссовского"
  - "Локомотив"
  - "Измайлово"
  - "Соколиная гора"
  - "Шоссе Энтузисастов"
  - "Андроновка Оп"
  - "Андроновка"
 durationOfTrainStop: 6000
 durationOfBlock: 12000



