openapi: 3.0.0
info:
  version: 1.0.0
  title: niias
paths:
  /schedule:
    get:
      summary: 'Возвращает объект "Расписание"'
      parameters:
        - name: data
          in: query
          description: Дата расписания
          required: true
          schema:
            type: object
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    id:
                      type: integer
                      example: 1

                    schedule trainnumber:
                      type: integer
                      example: 2

                    schedule drivernumber:
                      type: integer
                      example: 3

                    schedule stationfrom:
                      type: integer
                      example: 10

                    schedule timefrom:
                      type: object

                    schedule stationto:
                      type: integer
                      example: 11

                    schedule timeto:
                      type: object

        400:
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bad request


        404:
          description: Not founds
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not founds

    post:
      summary: 'Добавляет объект "Расписание"'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1

                schedule trainnumber:
                  type: integer
                  example: 2

                schedule drivernumber:
                  type: integer
                  example: 3

                schedule stationfrom:
                    type: integer
                    example: 10

                schedule timefrom:
                    type: object

                schedule stationto:
                    type: integer
                    example: 11

                schedule timeto:
                    type: object

      responses:
        200:
          description: OK

        400:
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string