openapi: 3.0.0
info:
  version: 1.0.0
  title: niias
paths:
  /schedule:
    get:
      summary: 'Возвращает объект "Расписание"'
      parameters:
        - name: data
          in: query
          description: Дата расписания
          required: true
          schema:
            type: object
            default: false
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/schedule'

    post:
      summary: 'Добавляет объект "Расписание"'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/schedule'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: OK

components:
  schemas:
    schedule:
      description: Объект "Расписание"
      type: object
      properties:
        id:
          type: integer
          format: int64

        schedule trainnumber:
          type: integer
          format: int64

        schedule drivernumber:
          type: integer
          format: int64

        schedule stationfrom:
          type: integer
          format: int64

        schedule timefrom:
          type: string
          format: 'date-time'

        schedule stationto:
          type: integer
          format: int64

        schedule timeto:
          type: string
          format: 'date-time'