openapi: 3.0.0
info:
  version: 1.0.0
  title: niias
paths:
  /schedule:
    get:
      summary: 'Возвращает объект "Расписание"'
      parameters:
        - name: data
          in: query
          description: Дата расписания
          required: true
          schema:
            type: object
            default: false
        - name: trainNumber
          in: query
          description: Номер поезда
          required: true
          schema:
            type: integer
            default: false
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Schedule'

    post:
      summary: 'Добавляет объект "Расписание"'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Schedule'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: OK

  /schedule/list:
    get:
      summary: "Возвращает список расписаний"
      parameters:
        - name: startDataTime
          in: query
          description: Начало промежутка поиска расписания
          required: true
          schema:
            type: object
            default: false
        - name: endDataTime
          in: query
          description: Конец промежутка поиска расписания
          required: false
          schema:
            type: object
            default: false
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ScheduleList'



components:
  schemas:
    CodsOfTechnicalOperationWithTrains:
      description: Список операций с составом
      type: string
      enum:
        - 1 - TRAINSERVICE
        - 2 - WASHING
        - 3 - DRYCLEANING
        - 4 - BASICCLEANING
        - 5 - EQUIPMENT
        - 6 - WASHINGANDDRYCLEANING
        - 7 - EQUIPMENTANDBASICCLEANING
        - 8 - MAINTENANCE2
        - 9 - MAINTENANCE3
        - 10 - ENGINEERINGWORKS

    ScheduleList:
      description: Список расписаний
      type: array
      items:
        $ref: '#/components/schemas/Schedule'

    Schedule:
      description: Объект "Расписание"
      type: object
      properties:
        id:
          type: integer
          format: int32

        codOfTechnicalOperationWithTrains:
          type: integer
          format: int32

        trainNumber:
          type: integer
          format: int32

        trainIndex:
          type: integer
          format: int32

        countTrainOnLine:
          type: integer
          format: int32

        sequentialNumberOfBrigade:
          type: integer
          format: int32

        driverNumber:
          type: integer
          format: int64

        codeOfDepartureStation:
          type: integer
          format: int64

        codeOfDepartureStationWithBrigade:
          type: integer
          format: int64

        departureTime:
          type: string
          format: 'date-time'

        departureTimeWithBrigade:
          type: string
          format: 'date-time'

        codeOfArrivalStation:
          type: integer
          format: int32

        codeOfArrivalStationWithBrigade:
          type: integer
          format: int32

        arrivalTime:
          type: string
          format: 'date-time'

        arrivalTimeWithBrigade:
          type: string
          format: 'date-time'

        codeOfHeadWagon:
          type: string